<form enctype="multipart/form-data" class="frmEditPDF">



<div class="panel panel-info" id="divEditPDF">
    <div class="panel-heading">
        <h4><b>Programa:</b> <?php echo $eP_nombreProg; ?></h4>
    </div>
    <div class="panel-body">
        <div class="row">
        
            <div class="col-md-12">
               
					<table align="center">
                    	<tr>
                        	<td width="450">
                        <div class="col-sm-9">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                            
                                <?php if(!empty($eP_documento)){ ?>
                                	<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px; padding-top:10px;">
                                    	<a href="pdf_programas/<?php echo $eP_documento; ?>" target="_blank">
                                        	<img src="img/pdf_gran.png" />
                                        </a>
                                    </div>
                                    <center>
                                        <label style="cursor:pointer; visibility:hidden;">
                      <input style="margin-top:-1px; vertical-align:middle;" type="checkbox" name="chkEP_flPDF" checked="checked"> Eliminar
                                        </label>
                                        <input type="button"  id="btnEP_CargaPDF" class="btn btn-primary" value="Eliminar" 
                                        onclick="procesoEnviaForm('frmEditPDF', 'process/procesoEditPDF.php', 'btnEP_CargaPDF', 'divEditPDF')">
                                    </center>
                                
								<?php }else{ ?>

                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                    <div>
                                      <span class="btn btn-default btn-file">
                                        <span class="fileinput-new">Seleccionar</span>
                                        <span class="fileinput-exists">Cambiar</span>
                                        <input type="file" name="flPDF" accept="application/pdf">
                                      </span>
                                      <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remover</a>
                                      <input type="button"  id="btnEP_CargaPDF" class="btn btn-primary" value="Subir PDF" 
                                      onclick="procesoEnviaForm('frmEditPDF', 'process/procesoEditPDF.php', 'btnEP_CargaPDF', 'divEditPDF')">
                                    </div>

                                <?php } ?>
                                
                            </div>
                        </div>
                        	</td>
                       </tr>
                    </table>
                
            </div>
            
        </div>
    </div>
    
</div>

</form>