<div class="panel panel-info">
    <div class="panel-heading">
        <h4>Servicios de Hotel</h4>
    </div>
    <div class="panel-body">
        <div class="row">
        
            <div class="col-md-12">
            
                 <ul class="gallery list-unstyled">
                 	
                    <?php if($aS_rest==1){ ?> 
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/restaurant.jpg" /> Restaurant</label>
                    </li>
                    
					<?php } if($aS_lavan==1){ ?>
             
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/lavanderia.jpg" /> Lavander&iacute;a</label>
                    </li>
             
             		<?php } if($aS_pDes==1){ ?>
                    
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/piscina_desc.jpg" /> Piscina descubierta</label>
                    </li>
                    
                    <?php } if($aS_tenis==1){ ?>
             
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/tenis.jpg" /> Cancha de tenis</label>
                    </li>
                    
                    <?php } if($aS_bar==1){ ?>
             
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/bar.jpg" /> Bar</label>
                    </li>
                    
                    <?php } if($aS_business==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/business_center.jpg" /> Business center</label>
                    </li>
                    
                    <?php } if($aS_spa==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/spa.jpg" /> Spa</label>
                    </li>
                    
                    <?php } if($aS_guarderia==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/guar_inf.jpg" /> Club de ni&ntilde;os</label>
                    </li>
                    
                    <?php } if($aS_cafet==1){ ?>
               
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/cafeteria.jpg" /> Cafeter&iacute;a</label>
                    </li>
                    
                    <?php } if($aS_intHot==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/internet.jpg" /> Internet hotel</label>
                    </li>
                    
                    <?php } if($aS_gym==1){ ?>
               
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/gimnasio.jpg" /> Gimnasio</label>
                    </li>
                    
                    <?php } if($aS_salasReu==1){ ?>
               
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/salones.jpg" /> Salas de reuni&oacute;n</label>
                    </li>
                    
                    <?php } if($aS_sHab==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/room_service.jpg" /> Servicio a la habitaci&oacute;n</label>
                    </li>
                    
                    <?php } if($aS_est==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/estacionamiento.jpg" /> Estacionamiento</label>
                    </li>
                    
                    <?php } if($aS_pCub==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/piscina_cubierta.jpg" /> Piscina cubierta</label>
                    </li>
                    
                    <?php } if($aS_jardin==1){ ?>
              
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/jardines.jpg" /> Jard&iacute;n</label>
                    </li>
                    
                    <?php } if($aS_disca==1){ ?>
                
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/acceso_discap.jpg" /> Discapacitados</label>
                    </li>
                    
                    <?php } if($aS_baut==1){ ?>
               
                    <li class="mix" style="display: inline-block; opacity: 1;">
                        <label><img src="iconos/hotel/shopping.jpg" /> Boutique</label>
                    </li>
                    
                    <?php } ?>
                </ul>  
            </div>
            
        </div>
    </div>
</div>






<div class="panel panel-info">
    <div class="panel-heading">
        <h4>Servicios Habitaci&oacute;n</h4>
    </div>
    <div class="panel-body">
        <div class="row">
        
            <div class="col-md-12">
            
                <ul class="gallery list-unstyled">
                		<?php if($aS_acond==1){ ?>
                    	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/aire_acondicionado.jpg" /> Aire acondicionado</label>
                            </li>
                            
                            <?php } if($aS_cFuerte==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/caja_de_seguridad.jpg" /> Caja fuerte</label>
                            </li>
                            
                            <?php } if($aS_tvCable==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/tv_cable.jpg" /> Televisi&oacute;n por Cable</label>
                            </li>
                            
                            <?php } if($aS_secPelo==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/secador.jpg" /> Secador de pelo</label>
                            </li>
                            
                            <?php } if($aS_calefac==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/calefaccion.jpg" /> Calefaci&oacute;n</label>
                            </li>
                            
                            <?php } if($aS_mBar==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/minibar.jpg" /> Mini bar</label>
                            </li>
                            
                            <?php } if($aS_fono==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/telefono.jpg" /> Tel&eacute;fono</label>
                            </li>
                            
                            <?php } if($aS_barraSeg==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/barradeseguridad.jpg" /> Barra de Seguridad</label>
                            </li>
                            
                            <?php } if($aS_noFuma==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/habitacion_no_fum.jpg" /> No fumadores</label>
                            </li>
                            
                            <?php } if($aS_tele==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/tv.jpg" /> Televisi&oacute;n</label>
                            </li>
                            
                            <?php } if($aS_interHab==1){ ?>
                        
                        	<li class="mix" style="display: inline-block; opacity: 1;">
                            	<label><img src="iconos/hotel/internet.jpg" /> Internet en Habitaci&oacute;n</label>
                            </li>
                            
                            <?php } ?>
                        
                   </ul>     
                
            </div>
            
        </div>
    </div>
    
   
</div>