<div id="page-content">
    <div id='wrap'>
        <div id="page-heading">

            <!-- <ol class="breadcrumb">
                    <li><a href="index.php">Dashboard</a></li>
                    <li>UI Components</li>
                    <li class="active">Tabs &amp; Accordions</li>
            </ol> -->

            <h1>CONSULTAR RESERVAS</h1>

        </div>
		
        
        <div class="container">

			

            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-danger">
					  
					  
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Buscar booking</h4>
                            </div>
                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-md-12">

                                        <form method="post" id="frmConsRes" action="process/procesoConsRes.php">
                                            <table align="center" cellspacing="5" cellpadding="5">
                                                <tr>
                                                    <td>Fecha desde:</td>
                                                    <td>
                                                        <input type="text" id="txtFechaDesde-ConsRes" name="txtFechaDesde-ConsRes" style="width:100px" value="<?php echo $this->CR_fechaIni; ?>">
                                                    </td>
                                                    <td>Fecha hasta:</td>
                                                    <td>
                                                        <input type="text" id="txtFechaHasta-ConsRes" name="txtFechaHasta-ConsRes" style="width:100px" value="<?php echo $this->CR_fechaFin; ?>">
                                                    </td>
                                                    <td rowspan="2">&nbsp;&nbsp;&nbsp;
                                                        <input type="button"  id="btnConsBooking" class="btn btn-primary" value="Buscar">
                                                        <img id="imgLoading" src="iconos/loading.gif" style="display:none" width="32" border="0" />
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>Fecha reserva:</td>
                                                    <td><input type="radio" id="rdbReserva" name="rdbFecha" value="1" <?php echo $rdbRes; ?>></td>
                                                    <td>Fecha viaje:</td>
                                                    <td><input type="radio" id="rdbViaje" name="rdbFecha" value="2" <?php echo $rdbVia; ?>></td>
                                                </tr>
                                            </table>
                                        </form>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                    <?php
                    if(!empty($_SESSION["sess_pCR_fechaDesde"]))
                    {
                    ?>
                    <script>
                        $('#btnConsBooking').delay( 10 ).fadeOut( 10 );
                        $('#btnConsBooking').animate({
                                                        'display': 'none'
                                                });
                        $('#imgLoading').fadeIn( 100 );
                        $('#imgLoading').animate({
                                                    'display': 'block'
                                            });
                    </script>
                    
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">Carta de confirmaci&oacute;n</h4>
                                </div>

                                <div class="modal-body" id="divCartaConfirm"></div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                    <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->

                    
                    
                    
                    <div class="panel panel-sky" id="contenedorBusqueda" style="display:none">
                        <div class="panel-heading">
                            <h4>Resultado de la busqueda</h4>
                        </div>
                        <div class="panel-body collapse in">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                                <thead>
                                    <tr style="background-color:#76c4ed;">
                                        <th width="45">Status</th>
                                        <th>F. Reserva</th>
                                        <th>F. Viaje</th>
                                        <th width="120">N&deg; Reserva</th>
                                        <th>Agencia</th>
                                        <th>Nombre Pasajero</th>
                                        <th>Total</th>
                                        <th>Voucher</th>
                                        <th>Confirmaci&oacute;n</th>
                                    </tr>
                                </thead>
                                <tbody>
                                
                                 <?php
                                    //echo $_SESSION["sess_pAP_ciudad"];

                                    //echo $_SESSION['sess_sp_acceso'].' - '.$_SESSION["sess_clave_usuario"];
                                    //echo '<br>';
                                    $var_getConsRes= $privateFunctions->getConsRes(
									$functions->invertirFecha($_SESSION["sess_pCR_fechaDesde"], '/', '-'), 
									$functions->invertirFecha($_SESSION["sess_pCR_fechaHasta"], '/', '-'), 
									$_SESSION["sess_pCR_tipoFecha"],
									$_SESSION['sess_sp_acceso'], 
									$_SESSION["sess_clave_usuario"]);
                                    if($var_getConsRes!=FALSE)
                                    { 
                                        foreach($var_getConsRes as $columRes)
                                        {
                                            $valorVenta =intval($columRes["totventa"]);
                                            $valorPago =intval($columRes["totpag"]);
                                            $cR_moneda = trim($columRes["moneda"]);
                                            $cR_fecha= trim($columRes['fecha']);
                                            $cR_fViaje= trim($columRes['f_viaje']);
                                            $cR_nFile= trim($columRes['num_file']);
                                            $cR_agencia= trim($columRes['agencia']);
                                            $cR_nomPax= trim($columRes['nompax']);
                                            $cR_totVenta= $functions->formatoValor($cR_moneda, trim($columRes['totventa']));

                                            $cR_codProg= $privateFunctions->getCodPak_numFile($cR_nFile);
                                            $cR_codBloq= $privateFunctions->getCodBloq_numFile($cR_nFile);


                                            $cR_estado= trim($columRes['estado']);
                                            $imgStatus='';
                                            if($cR_estado<>'N' && $valorPago < ($valorVenta -1))
                                            {
                                                $imgStatus= '<img src="iconos/st_amarillo.png" title="Pendiente de pago" />';
                                            }
                                            elseif($cR_estado<>'N' && $valorPago >= ($valorVenta -1))
                                            {
                                                $imgStatus= '<img src="iconos/st_verde.png" title="Pago realizado" />';
                                            }
                                            elseif($cR_estado=='N')
                                            { 
                                                $imgStatus= '<img src="iconos/st_rojo.png" title="Anulado" />';
                                            }


                                            $voucherStatus='';
                                            if($cR_estado<>'N' && $valorPago >= ($valorVenta -1))
                                            { 
                                                $voucherStatus='<a href="html2pdf/generar_vouchea.php?num_file='.$cR_nFile.'" target="_blank" onclick="window.open(this.href, this.target, \'width=896, height=600,left = 200,top = 100\'); return false;">
                                                <img src="iconos/pdf.png" alt="edit" width="24" border="0" />
                                                </a>';
                                            }
                                        ?>
                                        <tr class="odd gradeX">
                                            <td align="center"><?php echo $imgStatus; ?></td>
                                            <td><?php echo $cR_fecha; ?></td>
                                            <td><?php echo $cR_fViaje; ?></td>
                                            <td><?php echo $cR_nFile; ?></td>
                                            <td><?php echo $cR_agencia; ?></td>
                                            <td><?php echo $cR_nomPax; ?></td>
                                            <td><?php echo $cR_totVenta; ?></td>
                                            <td align="center"><?php echo $voucherStatus; ?></td>
                                            <td align="center">
                                                    <a data-toggle="modal" href="#myModal" onClick="abreCartaConfirm('<?php echo $cR_nFile; ?>', '<?php echo $cR_codProg; ?>', '<?php echo $cR_codBloq; ?>');"><img src="iconos/search.png" width="24" border="0" /></a>
                                            </td>
                                        </tr>
                                            <?php 
                                        }
                                    }
                                    else
                                    {
                                    ?>
                                        <tr>
                                            <td align="center" colspan="9">
                                            	No se encontraron registros
                                            </td>
                                        </tr>
                                    <?php
                                    }
                                    ?>
                                    
                                    
                                    
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                    
                    
                    <script>
                        $('#btnConsBooking').fadeIn( 100 );
                        $('#btnConsBooking').animate({
                                                        'display': 'block'
                                                    });

                        $('#imgLoading').delay( 10 ).fadeOut( 10 );
                        $('#imgLoading').animate({
                                                    'display': 'none'
                                                });

                        $('#contenedorBusqueda').fadeIn( 2000 );
                        $('#contenedorBusqueda').animate({
                                                            'display': 'block'
                                                        });
					
                    </script>
                    <?php } ?>
                </div>
            </div>
            
            

        </div> <!-- container -->
    </div> <!--wrap -->
</div> <!-- page-content -->